apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: wildcard-cert
spec:
  secretName: wildcard-cert
  dnsNames:
    - '*.mydomain.example.com'
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
